### ISSUE TITLE
MusicMetrics

### ISSUE THREAD

**Issue by Bachstelze** [abhishekbanthia/Awesome-APIs#10]
is developer.musicmetric.com down or fusty?

**Comment by abhishekbanthia** [comment]
I'm getting a 404 too. I've tweeted to them; will update the list depending on the reply.

**Comment by Bachstelze** [comment]
perhaps you need an account https://my.wpengine.com/ but this also doesen't work

**Comment by abhishekbanthia** [comment]
Haven't heard back & looks like Apple actually bought the thing. Removing.

More Info: https://techcrunch.com/2015/01/21/apple-musicmetric/
Commit Info: b4b91a435
