### ISSUE TITLE
Add File Storage and Manipulation

### ISSUE THREAD

**Issue by 007Cat24** [abhishekbanthia/Awesome-APIs#18]
Dropbox: https://www.dropbox.com/developers
Amazon S3: https://aws.amazon.com/de/documentation/s3/
Cloudinary: http://cloudinary.com/documentation

Free tier: 75,000 total images or videos and 7,500 monthly transformations, 2GB storage, 5GB bandwidth/month
Pros: free tiers includes images and videos manipulations (resizing, effects, overlays, optimization), backup and revisions, supports PDF, sprites, animated GIFs, etc. Provide SDK in multiple languages
Limitations: free tier does not offer custom domain

Filestack: https://filestack.com/docs/getting-started

Free tier: 250 file uploads/month, 500 file transformations/month, 3GB bandwidth/month
Pros: image and video transformations, document file conversions, audio/video transcoding, free CDN, HTML widget, iOS SDK, tons of cloud storage integrations
Limitations: file upload size limited to 50 MB, free tier does not offer custom CNAME, S3 as file source is premium feature

**Comment by abhishekbanthia** [comment]
This looks great. Can you update the Readme and issue a PR?

**Comment by 007Cat24** [comment]
Yeah, I'll do that in an hour.

**Comment by abhishekbanthia** [comment]
Commit Info: 3e61a2c8c
