### ISSUE TITLE
How do I update my fork with the newest updates to the main repo?

### ISSUE THREAD

**Issue by daneelrakow** [abhishekbanthia/Awesome-APIs#24]
Sorry, but this is my first open source project that I'm helping with and I don't know how to update my fork.

Do I just delete my fork and re-fork?

**Comment by abhishekbanthia** [comment]
You don't need to delete your fork.

Here's a very good SO answer I used previously:

http://stackoverflow.com/questions/20984802/how-can-i-keep-my-fork-in-sync-without-adding-a-separate-remote/21131381#21131381

**Comment by daneelrakow** [comment]
Thanks!
