### ISSUE TITLE
Microsoft Cognitive Services APIs are missing

### ISSUE THREAD

**Issue by kumardeepakr3** [abhishekbanthia/Awesome-APIs#26]
Microsoft has brilliant set of APIs for Speach, Vision, Language, Search, Knowledge and they work pretty well. Kindly add those as well. Should I add them?
https://www.microsoft.com/cognitive-services/en-us/apis

**Comment by abhishekbanthia** [comment]
I can't believe I missed those. Thanks for pointing out. You can add them and send me a PR.

**Comment by kumardeepakr3** [comment]
Oops. My Mistake. The APIs are covered under Machine Learning section as "Microsoft Azure Machine Learning API". I think the link should point directly to cognitive services page rather than to azure. Azure's page is rather confusing. Will change it to the correct heading and link to Microsoft Cognitive Services and send PR.
