### ISSUE TITLE
Would it make sense to add also API-design and discovery tools such as Swagger/OpenAPI?

### ISSUE THREAD

**Issue by vzaccaria** [abhishekbanthia/Awesome-APIs#38]
see for example [Swagger.io](http://swagger.io/).

**Comment by abhishekbanthia** [comment]
That's a great suggestion. [Postman](https://www.getpostman.com/) is another great app that I use for testing my APIs.

If you can add a new category near the end of the file about API Design and Discovery, I'd happily review and accept it.
