### ISSUE TITLE
Add new category: Retail

### ISSUE THREAD

**Issue by caroso1222** [abhishekbanthia/Awesome-APIs#47]
I think it would make sense to add Retail APIs such as Amazon Product Advertising API, Walmart API, Taobao API, etc. These APIs are useful to lookup and search products from the respective stores, advertise and monetize from within a third-party website, etc.

If this makes sense, I can open a PR with this new category and add some APIs I know and have used.

**Comment by 007Cat24** [comment]
That'a a good idea! These are very useful :)

**Comment by abhishekbanthia** [comment]
Sure @caroso1222 throw me a PR; I'll review and add them to the list 💯

**Comment by snetts** [comment]
And also Payment System APIs, like PayPal, Stripe, Google Wallet for Android and more
